# FROM node:22-slim AS base
# ENV PATH="/pnpm:$PATH"
# RUN corepack enable

# FROM base AS build
# COPY . /usr/src/app
# WORKDIR /usr/src/app
# RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
# RUN pnpm run -r build
# RUN pnpm deploy --legacy --filter=web --prod /prod/web

# FROM base AS web
# COPY --from=build /prod/web /prod/web
# WORKDIR /prod/web

# EXPOSE 4173
# CMD ["pnpm", "serve", "--", "--host", "0.0.0.0", "--port", "4173"]


FROM node:22-slim AS base
ENV PATH="/pnpm:$PATH"
RUN corepack enable

FROM base AS build
WORKDIR /usr/src/app
COPY . .
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
RUN pnpm -C apps/web build

FROM base AS web
WORKDIR /usr/src/app
COPY --from=build /usr/src/app /usr/src/app

WORKDIR /usr/src/app/apps/web
EXPOSE 4173
CMD ["pnpm", "serve", "--", "--host", "0.0.0.0", "--port", "4173"]
